---

- hosts: web1
  become: true
  tasks:
      - name: "Shell command"
        tags: webserver1
        shell: echo "This is a test file" > x1.txt
        args:
                chdir: /tmp
                executable: /bin/bash
        register: shell_output
      - debug: var=shell_output

      - name: create a text file in $HOME with the /bin/bash shell
        tags: webserver1
        shell: echo "Hello, World!" > $HOME/test_file.txt
        register: shell_output

      - debug: var=shell_output
