---

- hosts: all
  become: true
  pre_tasks:
           - name: updates package indexes
             tags: always
             yum:
                  update_only: yes
                  update_cache: yes


- hosts: web1
  become: true
  tasks:
        - name: Install php package
          tags: webserver1
          yum:
                  name: php
                  state: latest

- hosts: web2
  become: true
  tasks:
        - name: Install http package
          tags: webserver2
          yum:
                  name: 
                    - httpd
                    - samba
                    - unzip  
                  state: latest
- hosts: web2
  become: true
  tasks:
        - name: copy file 
          tags: webserver2
          copy:
                  src: t1.txt
                  dest: /home/ec2-user/
                  owner: ec2-user
                  group: ec2-user
                  mode: 0644

